-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jan 24, 2019 at 03:19 PM
-- Server version: 10.1.37-MariaDB
-- PHP Version: 7.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `board_db1`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `product_id` int(11) NOT NULL,
  `product_name` varchar(70) NOT NULL,
  `product_price` double NOT NULL,
  `product_desc` varchar(1500) NOT NULL,
  `product_img` varchar(100) NOT NULL,
  `product_age` int(11) NOT NULL,
  `product_min_players` int(11) NOT NULL,
  `product_max_players` int(11) NOT NULL,
  `product_category` varchar(50) NOT NULL,
  `product_difficulty` varchar(50) NOT NULL,
  `product_playtime` int(11) NOT NULL,
  `product_classic` tinyint(1) NOT NULL,
  `product_travelversion` tinyint(1) NOT NULL,
  `product_kickstarter` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_desc`, `product_img`, `product_age`, `product_min_players`, `product_max_players`, `product_category`, `product_difficulty`, `product_playtime`, `product_classic`, `product_travelversion`, `product_kickstarter`) VALUES
(1, 'Mens erger je niet!', 19.99, 'Mens Erger Je Niet!, wie kent het niet? De originele uitvoering van het meest gespeelde spel! De manier om regenachtige zondagmiddagen door te komen, al is Mens Erger Je Niet eigenlijk altijd een vermakelijk spel. En denk erom als het niet gaat zoals je wilt: mens, erger je niet!\r\n\r\nHet speelbord is tweezijdig bedrukt: een kant voor kleinere gezelschappen (totaal 4 spelers), de andere kant voor grotere (totaal 6 spelers).\r\n\r\nInhoud\r\nSpelbord\r\n24 houten pionnen\r\n1 houten dobbelsteen\r\nSpelregels\r\n\r\nGeschikt voor 2 tot 6 spelers vanaf 6 jaar. ', 'mens_erger_je_niet.jpg', 6, 2, 6, 'bordspel', '', 20, 1, 0, 0),
(2, 'Monopoly', 39.99, 'Monopoly Classic is het beroemde vastgoedspel voor snelle onderhandelaars waarin spelers kopen, verkopen, onderhandelen en ruilen om de ultieme rijkdom te behalen. Deze versie van het spel Monopoly verwelkomt de badeend, de Tyrannosaurus Rex en de pinguin in de pionnenfamilie. Kies je pion, zet hem op Start en gooi de dobbelstenen! Er kan maar 1 winnaar zijn bij Monopoly. Ben jij degene die straks alles bezit?\r\n\r\nEigenschappen:\r\n\r\nSpeel Monopoly Classic.\r\nIn dit spel kunnen spelers kopen, verkopen, onderhandelen en ruilen om de ultieme rijkdom te behalen.\r\nIn dit spel maak je kennis met de badeend, de Tyrannosaurus Rex en de pinguin.\r\nHet spel bestaat uit een speelbord, acht pionnen, 28 eigendomsbewijzen, zestien kanskaarten, zestien Algemeen Fonds-kaarten, 32 huizen, twaalf hotels, twee dobbelstenen, speelgeld en spelregels.', 'monopoly.jpg', 8, 2, 6, 'bordspel', '', 120, 1, 0, 0),
(3, 'Exploding Kittens', 24.99, 'Exploding Kittens is een fantastisch kaartspel voor mensen die van katten, explosies, laserstralen en soms ook van geiten houden. Dit tactische spel is een variant van Russisch roulette, maar dan met exploderende kittens. Je neemt kaarten van de stapel totdat je 1 van de gevreesde exploderende kittens trekt. Dan heb je meteen verloren. Met alle andere kaarten kun je jezelf verdedigen, aanvallen, een beurt overslaan of de katten afleiden. Alle kaarten zijn voorzien van hilarische illustraties van The Oatmeal.\r\n\r\nKenmerken van Exploding Kittens:\r\n- De box bevat 56 kaarten\r\n- Orginal edition\r\n- Engelstalig kaartspel Klik hier voor de Nederlandse editie\r\n- Eenvoudig te leren\r\n- Dit familievriendelijke partyspel was het meest succesvolle project ooit op Kickstarter\r\n- Deze box, zoals 99.99% van alle boxen, meowt niet!', 'exploding_kittens.jpg', 7, 2, 5, 'kaartspel', '', 15, 0, 0, 1),
(4, 'Bananagrams', 15, 'Bananagrams is een leuk anagrammen-woordspel in een grappige verpakking! Een etui (in de vorm van een banaan) bevat 144 blokjes met letters. Elke speler pakt willekeurig 21 blokjes uit deze voorraad en probeert zoveel mogelijk woorden te maken, waarbij elk woord een ander woord moet raken. Wanneer een speler zijn 21 letters heeft gelegd pakt elke speler 1 blokje uit de voorraad die ze moeten proberen aan te leggen. De speler die als eerste zijn letters kwijt heeft, wint dit leuke woordspel.', 'bananagrams.png', 5, 1, 8, 'denkspel', '', 15, 0, 0, 0),
(5, '30 Seconds', 29.95, 'Nederlandse editie van dit spectaculaire partyspel 30 Seconds voor teams. Fantastisch voor grote gezelschappen op feestjes en partijen.\r\nJe speelt in teams. Een van jullie probeert binnen 30 seconden zoveel mogelijk van de 5 begrippen op een kaartje te omschrijven. Hoe meer begrippen jullie raden, des te meer velden jullie op het speelbord vooruit mogen. Een dobbelsteenworp kan daar nog verandering in brengen. Welk team bereikt als eerste de finish? ', '30_seconds.jpg', 12, 3, 24, 'bordspel', '', 30, 0, 0, 0),
(6, 'Scrabble travel', 24.99, 'Nu kun je Scrabble overal mee naartoe nemen! Of je nu in de trein, in het vliegtuig of boven op een bergtop speelt, deze wereldwijde favoriet gaat altijd met je mee.\r\n\r\nHet bekende speelbord heeft bij Scrabble Travel opstaande randjes om de letterblokjes op hun plaats te houden - tijdens het spellen van de woorden blijft alles op zijn plaats! Scoor zo veel mogelijk punten door met de letterblokjes woorden te vormen. En let vooral op het gezicht van je tegenspeler als je een letterblokje op een vakje met drie maal woordwaarde legt!\r\n\r\nCompact en makkelijk mee te nemen. Waar je ook naartoe gaat, dit spel gaat overal met je mee!\r\nGeschikt voor 2 - 4 spelers.\r\nInclusief speelbord, 4 plankjes, 102 letterblokjes, letterzakje en spelregels.\r\nGeschikt voor spelers vanaf 10 jaar. ', 'scrabble.jpg', 12, 2, 4, 'bordspel', '', 90, 1, 1, 0),
(7, 'King of Tokyo', 29.95, 'Nederlandse uitgave van het bekende bordspel King of Tokyo van Richard Garfield!\r\n\r\nGa als gigantisch monster wild tekeer en vernietig alles op je pad! Gooi de dobbelstenen en vorm de juiste combinaties om aan te vallen, te herstellen, speciale kaarten te kopen of overwinningspunten te scoren. Het is aan jou om de beste strategie te vinden om King of Tokyo te worden en je tegenstanders uit te schakelen door een allesvernietigende aanval... De speler die als eerste 20 overwinningspunten verzamelt - of het laatst levende monster is - wint het spe en bemachtigt de troon van Tokyo!\r\n\r\nInhoud:\r\n- 1 Tokyo speelbord\r\n- 66 kaarten\r\n- 28 fiches\r\n- 8 dobbelstenen\r\n- 6 Monsterbordjes\r\n- 6 kartonnen figuren met plastic voetstukjes\r\n- Energieblokjes\r\n- Spelregels ', 'king_of_tokyo.jpg', 8, 2, 6, 'bordspel', '', 30, 0, 0, 0),
(8, 'Catan', 40, 'Vernieuwde editie van het bekende handelsspel de Kolonisten van Catan. Het spel bevat nu miniaturen en ook het artwork is volledig aangepast. Zo kun je je nog meer inleven in de wereld van Catan!\r\n\r\nIn 1999 werd dit populaire handelsspel tot Speelgoed van het Jaar verkozen. Het spel is voor iedereen leuk vanwege de interactie, het vleugje geluk en de tactische mogelijkheden.\r\n\r\nJe begint met 2 dorpen op een variabel speelbord met akkers, weiden, heuvels, bergen en bossen. Als je aan de beurt bent, gooi je met 2 dobbelstenen om te bepalen wie er grondstoffen krijgen. Dat is afhankelijk van de positie van je dorpen. Daarna mag je handelen met de bank of met je medespelers. Je krijgt namelijk niet alle soorten grondstoffen binnen. En die heb je wel nodig om nieuwe dorpen, straten en steden te bouwen. Je kunt ook ontwikkelingskaarten kopen om speciale acties te kunnen doen. Verder loopt er een struikrover rond die sommige landschappen leegrooft.\r\n\r\nDorpen en steden leveren niet alleen grondstoffen op, maar zijn ook punten waard. Ook ontwikkelingskaarten, de langste aaneengesloten route en de grootste riddermacht brengen punten binnen. Wie als eerste 10 punten heeft, wint het spel direct! ', 'catan.png', 10, 3, 4, 'bordspel', '', 90, 1, 0, 0),
(9, 'Escape Room: The game', 35.95, 'Voel de spanning met Escape Room the game en beleef nu het mysterie van een escape room als spel gewoon bij jou thuis!\r\n\r\nIn dit uitdagende en onvoorspelbare bordspel los je samen een mysterie op door te zoeken naar verborgen aanwijzingen en het oplossen van raadsels. Je hebt hiervoor slechts 1 uur de tijd, gebruik die tijd goed! De Chrono Decoder telt af van 60 naar 0, zorgt voor de benodigde sfeer en geeft af en toe cryptische aanwijzingen. Hebben jullie binnen 60 minuten de juiste code gevonden om bijvoorbeeld te ontsnappen uit de gevangenis, de atoombom te ontmantelen of het virus te stoppen, dan win je gezamenlijk het spel! Dit vereist echt teamwork en goede communicatie maar ook vindingrijkheid, creativiteit, logisch nadenken en aandacht voor details. Want niet elk raadsel, code of aanwijzing is zomaar eenvoudig te vinden en te interpreteren...\r\n\r\nAre you up for the Challenge?\r\n\r\nInhoud:\r\n\r\n    Chrono Decoder\r\n\r\n    Hint Decoder\r\n\r\n    16 sleutels\r\n\r\n    4 x 8 hintkaarten\r\n\r\n    4 verschillende Escape Rooms', 'escape_room.jpg', 16, 3, 5, 'denkspel', '', 60, 0, 0, 0),
(10, 'Munchkin', 23.99, 'Dood de monsters, jat de schat, verraad je maat\r\n\r\nJe begint als een niveau een mens zonder klasse. Maar naarmate het spel vordert kan je veranderen in een dwerg, elf, priester, magier en dief. Dit is Munchkin, een kaartspel dat de ultieme parodie is op Dungeons & Dragons. Vecht met monsters, verover de schat en pak ook de schat van je teamgenoten af. Alles om maar tot niveau tien te komen en het spel te winnen is geoorloofd.\r\n\r\nHet originele Engelstalige kaartspel, goed voor avonden lol! ', 'munchkin.jpg', 12, 3, 6, 'kaartspel', '', 90, 0, 0, 0),
(11, 'Trans Europa', 23.99, 'Een eenvoudig spoorweg-spel. Het spel bestaat uit meerdere rondes. Per ronde pakt iedere speler vijf toevallige steden. Hoe sneller jullie je vijf steden met een spoorweg verbinden, des te meer prestige jullie ervoor krijgen. Er staat niets meer in de weg voor een snelle promotie van spoorwegarbeider naar directeur van de spoorwegen!\r\nWinnaar is, de speler die na meerdere rondes als eerste 13 prestigepunten heeft.', 'trans_europa.jpg', 8, 2, 6, 'bordspel', '', 45, 0, 0, 0),
(12, 'Koehandel', 23.99, 'Boer zoekt koe! Hier vind je alles wat het onstuimige boerenhart begeert: dieren, veilingen en wat al niet meer! Haal je medespelers bij de koehandel flink het vel over de neus! Manipuleer de marktprijs van de dieren en beproef je geluk in de loterij! In het spel voor beginners is het met een beetje boerenverstand al meteen goed boeren. Maar in het spel voor gevorderden breekt bij kenners van de koehandel pas echt het beest los. 10 verschillende veilingen én de jonge dieren die voor het eerst van de partij zijn zorgen voor de nodige afwisseling. Dus, spring in je klompen en op naar de veemarkt!', 'koehandel.jpg', 10, 2, 4, 'kaartspel', '', 0, 0, 0, 0),
(13, 'Ticket to Ride Europe', 38.24, 'Met het Ticket to Ride Europe bordspel reis je per trein over het hele continent. Waag je een reis door de donkere tunnels in Zwitserland of aan boord van een veerboot op de Zwarte Zee? Of bouw je schitterende treinstations in de grote hoofdsteden van oude wereldrijken? \r\n\r\nIn Ticket to Ride Europe moeten de spelers de routes op hun bestemmingskaarten volbrengen. Dit doe je door verbindingen tussen steden te claimen, die je mag bouwen als je de juiste kaartencombinaties in handen hebt. Heb jij aan het eind van het spel de meeste punten verzameld met je treinnetwerk? Dan ben jij de winnaar. ', 'ticket_to_ride_europe.jpg', 8, 2, 5, 'bordspel', '', 60, 0, 0, 0),
(14, 'Code Names', 19.95, 'In Codenames kennen twee rivaliserende geheime diensten de geheime identiteit van de 25 spionnen. Hun teamgenoten kennen deze spionnen enkel bij hun codenaam.\r\n\r\nBeide teams gaan met elkaar de strijd aan en proberen als eerste contact te leggen met hun spionnen. Elk hoofd van de geheime dienst geeft aanwijzingen door één woord te noemen dat van betrekking is op meerdere worden op tafel. Zijn teamgenoten proberen de woorden van hun kleur te raden zonder daarbij spionnen van de tegenstander aan te wijzen. En natuurlijk wil iedereen wil uit de buurt van de huurmoordenaar blijven.\r\n\r\nEen uniek woordspel, waarbij spelers associaties met woorden moeten zoeken. Probeer met één woord een aanwijzing te bedenken die op meerdere woorden op tafel slaat, zodat je medespelers snel veel punten kunnen scoren. \r\nHoge herspeelbaarheid: 400 verschillende woorden waarvan er steeds slechts 25 in een spel worden gebruikt, waardoor de associaties die spelers kunnen maken steeds anders zullen zijn! \r\n\r\nEen spel voor twee teams (van onbeperkte grote), maar bevat ook regels voor 2 of 3 spelers. \r\n\r\nEen echte Nederlandstalige versie! Geen 1-op-1 vertaling van de Internationale versie, maar….woorden die uniek zijn voor Nederland en België (plaatsnamen, cultuur, eten en drinken), woorden die in het Nederlands en Vlaams meerdere betekenissen hebben en woorden die in onze taal tot de verbeelding spreken of in verschillende categorieën passen.', 'codenames.jpg', 10, 2, 8, 'bordspel', '', 15, 0, 0, 0),
(16, 'Rummikub Original Classic', 28.99, 'Productbeschrijving\r\nHet alombekende spel Rummikub! Maak mooie cijferreeksen met de gekleurde cijfers op je plankje. Wie legt de slimste combinaties? Ben jij degene die het eerst alle cijfers op tafel heeft liggen? Een spel dat inzicht, durf en tactiek combineert.\r\n\r\n\r\n\r\nSpelomschrijving\r\n\r\nSpelers moeten zo snel mogelijk de tegels op hun bordje kwijt zien te raken door de juiste combinaties te leggen. Dat kan met de tegels van je bordje of met de tegels die al op tafel liggen.\r\n\r\nIn Rummikub zijn de populairste elementen van een aantal bekende spelen, zoals Mah-Jongg, domino, jokeren en aspecten van het schaakspel verwerkt.\r\n\r\nDe houders voor de Rummikubstenen hebben vrolijke felle kleuren. Ook krijgt iedere speler voor elk goed aangelegde steen 1 beloningsfiche. De winnaar is degene met de meeste fiches.\r\nGeschiedenis\r\n\r\nRummikub was oorspronkelijk een kaartspel met twee stel kaarten. Dat kostte natuurlijk veel ruimte en dat was voor niet iedereen ideaal. Daarom werd er een nieuwe versie gemaakt waarbij er kleuren en cijfers gebruikt werden in plaats van de gebruikelijk 1-10, Boer-Aas in de 4 soorten. Zo ontstond Rummikub zoals wij het nu kennen en spelen.\r\n\r\nh3>Inhoud\r\n- 106 steentjes\r\n- 4 plankjes\r\n- Spelregels', 'rummikub_original_classic.jpg', 6, 2, 4, 'denkspel', '', 60, 1, 0, 0),
(17, 'The Wall', 26.99, 'Met de elektronische muur en de kleurrijke ballen lijkt het net alsof je in de TV-show zit:\r\n• Houd de ballen boven op de muur\r\n• Laat ze los en kijk hoe ze naar beneden vallen\r\n• Beantwoord de vragen. Afhankelijk van het antwoord laat de spelmeester de muur groen of rood oplichten!\r\n\r\nInhoud:\r\nSpeelmateriaal: 1 elektronische lichtgevende muur* van ongeveer 32 cm hoogte, 180 kaarten met 660 vragen, 3 witte ballen, 3 groene ballen, 3 rode ballen, 3 strips met geldbedragen, 1 contractblok 1 scoreblok 1 spelhandleiding\r\n* Er zijn 2 batterijen (AAA, LR03, 1, 5V) nodig.', 'the_wall.jpg', 10, 3, 6, 'bordspel', '', 30, 0, 0, 0),
(18, 'Vertellis', 17.99, 'De Vertellis Feestdagen-editie is een vragenkaartspel dat families, vrienden, en collega’s op een speelse manier dichterbij elkaar brengt.\r\n\r\nDe vragen zijn het startsein voor diepgaande gesprekken en leuke verhalen. De Feestdagen-editie is ideaal om aan het einde van het jaar, bijvoorbeeld met Kerst en Oud & Nieuw te spelen.\r\n\r\nZo komt met Vertellis saamhorigheid, liefde en begrip op 1, in plaats van de overdaad aan hapjes, drankjes en versiering!\r\n\r\nGoede gesprekken zijn echter niet alleen leuk en fijn tijdens de decembermaand, maar ALTIJD! De Feestdagen-editie kan op elk moment uit de kast gehaald worden om te reflecteren op de afgelopen periode en vooruit te blikken naar de komende tijd. De periode waarop je terug- of vooruitblikt kan je helemaal zelf bepalen!\r\n\r\nEen paar voorbeeldvragen zijn:\r\n\"Op welke eigen prestatie ben je het meest trots?\", \"Wat heb je niet bereikt, wat je wel had willen bereiken?\" en \"Wat ga je doen dat niemand van je verwacht?\"\r\n\r\nLaat die goede gesprekken maar komen!\r\n', 'vertellis.jpg', 8, 2, 10, 'kaartspel', '', 120, 0, 0, 0),
(20, 'Ramses', 19.95, 'De steenrijke, maar helaas wat verstrooide farao Ramses II heeft tijdens zijn leven onmetelijke rijkdommen vergaard en in zijn piramides verstopt. Maar helaas is hij het overzicht kwijt en weet hij niet meer waar hij wat verstopt heeft. Maar gelukkig zijn jullie er om hem te helpen alles terug te vinden!\r\n\r\nInhoud:\r\n47 Piramides\r\n30 Zoekkaarten\r\n1 Spelbord\r\n12 Schat panelen\r\n21 Fiches\r\n1 Mummie', 'ramses.jpg', 7, 1, 5, 'bordspel', '', 30, 0, 0, 0),
(21, 'Levensweg Elektronisch Bankieren', 28.95, 'Bij Levensweg Elektronisch Bankieren gebruik je pasjes om te betalen.\r\n\r\nIn deze moderne versie van het bekende spel Levensweg regel je alle geldzaken met de elektronische geldautomaat. Geen cash geld, maar bankpasjes dus! Bewaar je miljoenen op je bankpasje en rij met je auto van start tot pensioen. Kies je levensweg en je stapt in een spel boordevol avontuur, gezinsleven en onverwachte verrassingen. Als iedereen gepensioneerd is, wint de rijkste speler. \r\n\r\nInhoud\r\n• Levensweg Elektronisch Bankieren\r\n• Speelbord\r\n• Draaiwijzer\r\n• 5 draai & win fiches\r\n• 4 auto\'s\r\n• 4 stapeltjes kaarten\r\n• 1 betaalautomaat\r\n• 4 elektronische bankpasjes', 'levensweg_elektronisch_bankieren.jpg', 8, 2, 4, 'bordspel', '', 60, 0, 0, 0),
(22, 'Speedcups ', 13.95, 'Concentratie-, reactie- en behendigheidsspel voor het hele gezin. Je krijgt 5 bekers in verschillende kleuren. Elke ronde draait een speler de bovenste kaart van de stapel om. Daarop staan 5 voorwerpen in de kleuren van de bekers horizontaal of verticaal georiënteerd. Zo kunnen er 5 vogels in een boom zitten of 5 shirts aan een waslijn. Je probeert nu zo snel mogelijk je bekers op of naast elkaar te zetten op de manier waarop dit op de kaart is aangegeven. Ben je als eerste klaar, druk dan snel op de bel. Heb je het goed, dan win je de kaart. De speler met de meeste kaarten wint het spel. Speed Cups heeft zeer eenvoudige spelregels, waardoor het snel te leren is. Leuk voor families met kinderen, maar ook voor studenten en veelspelers die iets luchtigs tussendoor willen doen.', 'speed_cup.jpg', 6, 2, 4, 'kaartspel', '', 15, 0, 0, 0),
(24, 'Party & Co Original', 20.95, 'Party & Co Original is een doldwaas spel, een geheid succesnummer op feestjes en spelletjesavonden. Het combineert de beste elementen van de leukste gezelschapsspellen. Het gaat er steeds om een van de vijf soorten opdrachten in het spel binnen 30 seconden te doen. \r\n\r\nNu met 2.000 nieuwe vragen en opdrachten. Kom maar op! Wedden dat je niet kunt ophouden met spelen… en lachen!\r\n\r\nGeschikt voor 3 tot 20 spelers vanaf 14 jaar.', 'party_&_co.jpg', 14, 3, 20, 'bordspel', '', 45, 1, 0, 0),
(25, 'Cards against humanity', 47.15, 'Cards Against Humanity (UK Editie) is eindelijk in Nederland gearriveerd!\r\n\r\nDit spel is een feestspel voor verschrikkelijke mensen. In tegenstelling tot alle andere kaartspellen die je ooit gespeeld hebt, is Cards Against Humanity net zo slecht en awkward als al jouw vrienden.\r\n\r\nHet spel is simpel. Elke ronde stelt één speler een vraag van een Black Card en de rest antwoordt met zijn of haar grappigste White Card. De speler die de vraag heeft gesteld, verzamelt alle antwoorden en leest de combinaties voor. Hij bepaalt welk antwoord hij het grappigst vindt. Diegene die het grappigste antwoord heeft gegeven, verdient hiermee een Awesome Point. \r\n\r\nDeze UK Edition van Cards Against Humanity bevat:\r\n• 550 kaarten (460 White cards en 90 Black cards);\r\n• Professioneel geprinte premium speelkaarten;\r\n• Spelregels en alternatieve regels, netjes in krimpfolie in een mooie box gepakt;\r\n• Aangepast van de Amerikaanse editie om meer Britse humor te verwezenlijken;\r\n\r\n0% van de opbrengsten gaan naar stichting Kinderen in Nood', 'cards_against_humanity.jpg', 16, 4, 30, 'kaartspel', '', 30, 0, 0, 1),
(26, 'Carcassonne', 22.95, 'In dit bekende legspel Carcassonne bouwen de spelers gezamenlijk de Franse stad Carcassonne op met al haar wegen, steden, kloosters en weiden. Door het inzetten van horigen scoren ze punten voor afgebouwde projecten. \r\n\r\nElke beurt in Carcassonne leg je één landtegel neer en mag je er één horige opzetten. Welke soort dat is, hangt van de tegel af. Zo zijn er tegels met wegdelen, kloosters, stadsdelen en/of stukken weide. In principe mag er niet meer dan één horige op een project staan, maar als twee onafgebouwde delen aan elkaar worden gebouwd, kan het toch voorkomen dat er meer horigen op terecht komen. Wie de meeste horigen op een afgebouwd project heeft, krijgt daar direct punten voor. Voor elke soort project gelden verschillende spelregels voor het aantal te ontvangen punten. Het spel is afgelopen als alle tegels zijn gelegd. Wie de meeste punten heeft, wint Carcassonne. \r\n\r\nCarcassonne is zowel bij families als bij veelspelers geliefd, omdat het ondanks de eenvoudige spelregels voldoende diepgang heeft. Het vleugje geluk geeft iedereen de mogelijkheid om tot het einde om de winst mee te doen.\r\n\r\nDoel van Carcassonne\r\nDoor het plaatsen van landtegels en horigen proberen de spelers zo veel mogelijk punten te vergaren. \r\n\r\nVoorbereiding Carcassonne\r\nDe starttegel wordt open op tafel gelegd. De andere tegels worden geschud en in gedekte stapeltjes verdeeld. Iedere speler krijgt 7 horigen in zijn kleur.\r\n\r\nSpelverloop Carcassonne\r\nEr wordt met de klok mee gespeeld. De speler,', 'carcassonne.jpg', 7, 2, 5, 'kaartspel', '', 35, 1, 0, 0),
(27, 'Stratego', 27.95, 'Stratego Original: Val aan en verover de vlag! Keer op keer probeert luitenant Jan Zonderland samen met zijn kameraden de vlag van de Roodjassen te veroveren. Het leger van de Blauwhemden is al behoorlijk verzwakt, maar de mannen geven niet op. Wil jij de luitenant helpen om het leger van de Roodjassen te verslaan? De Blauwhemden rekenen op een slimme strateeg als jij! Het doel van dit klassieke bordspel is om de vlag van je tegenstander te veroveren terwijl je je eigen vlag bewaakt. Je staat er gelukkig niet alleen voor; je hebt een heel leger tot je beschikking, plus een verleidelijke spionne en zes bommen. Eerst bedenk je een geheime opstelling voor jouw manschappen, waarna de spannende strijd losbarst. Om de vlag te veroveren ga je over tot de aanval. De rangen van de speelstukken bepalen of jij overwint... of het veld moet ruimen. Maar er dreigt nog meer gevaar. Want zodra jouw speelstuk een bom aantikt, is het einde oefening! \r\n\r\nBen jij dapper genoeg voor eindeloos strategisch speelplezier? Trek dan ten strijde met deze vernieuwde uitvoering van Stratego!\r\n\r\nBIJZONDERHEDEN\r\n• Met de originele voorbedrukte speelstukken\r\n• Snel van start met de Stratego quick start guide...\r\n• ...En de geheime oefenmissie om snel vertrouwd te raken met de rangen en spelregels\r\n\r\nINHOUD:\r\n• 40 bedrukte blauwe speelstukken\r\n• 40 bedrukte rode speelstukken\r\n• speelbord\r\n• scherm\r\n• 2 sorteerrekjes voor de speelstukken\r\n• 2 enveloppen met oefenmissies\r\n• spelregels inclusief quick start guid', 'stratego.jpg', 8, 1, 2, 'bordspel', '', 60, 1, 0, 0),
(28, 'Who\'s the dude?', 19.99, 'Hij is relaxed, onhandig en maakt de meest bizarre dingen mee. Het is de Dude! \r\n\r\nIn dit hilarische spel is de levensgrote (150 cm!) opblaasbare Dude je beste vriend. Beeld samen met hem zo veel mogelijk situaties uit. Speel bijvoorbeeld een scène uit een film na of beeld een sport of beroep uit. De andere spelers proberen binnen de tijd te raden wat jij allemaal met de Dude uitbeeldt. Dan is de volgende speler aan de beurt. De speler die na 4 rondes de meeste punten heeft, wint het spel!\r\n\r\nEn de Dude? Die wint altijd. Het spel waarin je het met elkaar doet!\r\n', 'who_is_the_dude.jpg', 16, 3, 8, 'overige', '', 20, 0, 0, 0),
(29, 'Boonanza', 10.95, 'In dit communicatieve kaartspel Boonanza handelen de spelers met hun bonen en verbouwen deze op hun akkers. Wie troggelt de andere spelers de beste bonen af en verdient het meeste geld?\r\n\r\nIedere speler krijgt 5 bonenkaarten en moet deze op volgorde in zijn hand houden. Verder heeft iedere speler twee bonenvelden. Op elk daarvan mag hij één soort bonen verbouwen. Als je aan de beurt bent, moet je de eerste kaart en mag je de tweede kaart uit je hand verbouwen. Daarna draai je twee nieuwe bonenkaarten open die je mag houden of verhandelen. Je mag ook kaarten uit je hand verhandelen. Dat kan nuttig zijn, want een bonenveld is meer waard als er meer kaarten van een soort op liggen. En als je een soort moet verbouwen die er niet ligt, moet je een ander verkopen. En dat kan wel eens te vroeg komen... \r\n\r\nJe kunt er per spel echter wel één keer voor kiezen om voor drie thalers een extra bonenveld te kopen. Het spel is afgelopen als de stapel bonenkaarten drie keer is doorgespeeld. Wie daarna het meeste geld heeft, wint. \r\n\r\nBoonanza is een fascinerend handelsspel van de auteur van Agricola en Le Havre en is een echte aanrader voor liefhebbers van bijvoorbeeld De Kolonisten van Catan.', 'boonanza.jpg', 12, 3, 5, 'kaartspel', '', 45, 0, 0, 0),
(30, 'Party & Co Family', 24.95, 'Met Party & Co Family imiteer, teken, wring je je in bochten, geef antwoord op originele vragen en overwin de grappigste uitdagingen. Heb de GROOTSTE LOL met de nieuwe Party & Co Family: EEN FEESTJE VOOR DE HELE FAMILIE!\r\n\r\nHet spel kan in teams (maximaal 3 teams van 2 of meer spelers) gespeeld worden of met maximaal 3 individuen. Verdeel de spelers in teams. Het kunnen teams van alleen volwassenen of alleen kinderen zijn of gemengd. Dat mogen jullie zelf weten. Kies met welke kant van het speelbord je wil spelen: het normale parcours duurt ongeveer 50 minuten. Het korte parcours ongeveer 25 minuten.\r\n\r\nAan het begin van de beurt gooit het team de dobbelsteen en verplaatst de pion naar het bijbehorende vakje. Vervolgens doet het team de opdracht die het vakje aangeeft. Wanneer een kind de opdracht gaat doen, pak dan een kaartje van de stapel kaartjes voor kinderen. Wanneer een volwassene de opdracht gaat doen, pak dan een kaartje van\r\nde stapel kaartjes voor volwassenen. Als er op het kaartje een hint bij de opdracht staat, dan mag je die gebruiken. ALS HET TEAM DE OPDRACHT GOED DOET, pakken ze een uitdagingskaart en spelen ze verder, maar dit keer moeten ze de nieuwe opdracht goed proberen te doen met de toegevoegde gekke uitdaging, zodat het moeilijker wordt. ALS HET TEAM DE OPDRACHT NIET GOED DOET, dan is het volgende team aan de beurt. Wanneer een team op het laatste vakje aankomt, dan moeten ze nog één laatste opdracht doen om te kunnen winnen. Daartoe pakken ze 3 uitdag', 'party_&_co_family.jpg', 8, 4, 8, 'bordspel', '', 50, 1, 0, 0),
(31, 'Catan het snelle kaartspel', 10.99, 'Vlot kaartspel voor 2-4 spelers, gebaseerd op het populaire bordspel De Kolonisten van Catan.\r\n\r\nOok in dit kaartspel bouwen de spelers straten, dorpen en steden en zetten ze ridders in. Steden kunnen op verschillende manieren uitgebreid worden. Verder kunnen de spelers met elkaar of met de markt en de gedekte stapel grondstoffen ruilen. Maar pas op: straten en ridders kunnen zomaar verloren gaan aan de andere spelers. Zo zijn ook behaalde overwinningspunten niet altijd zeker. Het bouwen van een kerk of een stadsmuur kan echter bescherming bieden!\r\n\r\nDoor de relatief eenvoudige spelregels kunnen kinderen vanaf 8 jaar al meedoen!', 'catan_snel_kaartspel.jpg', 8, 2, 4, 'kaartspel', '', 90, 0, 0, 0),
(32, 'Halli Galli Extreme', 13.95, 'Iedere speler krijgt een gedekte stapel kaarten. Op elke kaart staan één of meer vruchten of een dier. Om beurten draait iedere speler een kaart om en legt deze op zijn eventueel eerder omgedraaide kaarten. Zo is voor iedere speler altijd maar één kaart zichtbaar. De spelers proberen op de bel te drukken als:\r\nEr twee gelijke vruchtenkaarten zichtbaar zijn\r\nEr een olifant zichtbaar is, maar geen aardbeien\r\nEr een aap zichtbaar is, maar geen citroenen\r\nEr een varken zichtbaar is\r\nWie dat als eerste doet, krijgt alle open kaarten. Wie geen kaarten meer heeft, is uitgeschakeld. Wie blijft als laatste over? Halli Galli Extreme maakt het bekende spel met de bel nog chaotischer en hilarischer. Wanneer moet je bellen en wanneer juist niet? Opletten geblazen dus!', 'halli_galli_extreme.jpg', 8, 2, 6, 'kaartspel', '', 20, 0, 0, 0),
(33, 'Buurman & Buurman Kwartet', 8.95, 'Speel kwartet met Buurman en Buurman en maak de meeste kwartetten om het spel te winnen.\r\n', 'buurman_kwartet.jpg', 3, 2, 4, 'kaartspel', '', 15, 0, 0, 0),
(34, 'Scrabble Original', 28.95, 'Scrabble is een leuk spel voor de gehele familie. In Scrabble probeert iedere speler zoveel mogelijk punten te behalen. Hiervoor hebben zij echter maar beperkt de tijd, wanneer de letters op zijn is het spel voorbij. Iedere letter heeft zijn eigen waarde en de letters gebruik je om complete woorden mee te leggen. Zorg dat je handig gebruik maakt van het speelbord door worden te leggen op letter- en woordverdubbelaars. De speler die met de meeste punten eindigt wint!', 'scrabble_original.jpg', 10, 2, 4, 'bordspel', '', 90, 1, 0, 0),
(35, 'Perudo', 22.95, 'Perudo is een verrassend, eenvoudig en snel blufspel vol spanning. Schud de dobbelstenen in je beker, draai hem om op tafel, gluur naar je eigen score en gok hoeveel dobbelstenen van een bepaald getal minimaal op tafel liggen. Ben jij de grootste bluffer? Perudo win je door het beste te bluffen en door goed te gokken wat de andere spelers hebben gegooid. Ervaar de spanning van dit eeuwenoude blufspel! ', 'perudo.jpg', 8, 2, 4, 'dobbelspel', '', 30, 0, 0, 0),
(36, 'Cool Runnings', 15.99, 'De coolste wedstrijd aller tijden! Welk ijsblokje bereikt de finish? Wie overleeft de aanvallen in de hitte van de strijd? Hier geldt: wie smelt, verliest!', 'cool_runnings.jpg', 8, 2, 4, 'overige', '', 30, 0, 0, 0),
(37, 'EXIT Het Vergeten Eiland', 13.99, 'Het uitdagende coöperatieve escape room-spel! Ontsnap zo snel mogelijk van het vervloekte eiland. Probeer binnen anderhalf uur alle puzzels op te lossen en alle codes te breken. Alleen dan ontsnappen jullie uit de locatie waar jullie opgesloten zitten. Logisch nadenken en doorzettingsvermogen zijn vereist om dit spel tot een goed einde te brengen. En komen jullie er echt niet uit, dan bevat het spel tipkaarten om jullie op het goede spoor te brengen. EXIT: Het Vergeten Eiland is maar één keer speelbaar omdat het speelmateriaal moet worden beschreven, gevouwen of afgescheurd. Maar net als in een \"echte\" escape room garanderen we een zeer intense puzzel- en speelervaring! De puzzels zijn vrij pittig. Daardoor is het spel vooral geschikt voor fervente puzzelaars en escape room-liefhebbers.', 'exit_het_vergeten_eiland.jpg', 12, 1, 4, 'denkspel', '', 45, 0, 0, 0),
(38, 'Uno', 9.95, 'Het doel van dit spel? Troef de eerder gespeelde kaart met een kaart van dezelfde kleur of hetzelfde symbool. Maar let goed op de actiekaarten en hou het bluffen van de tegenstander in de gaten!', 'uno.jpg', 7, 2, 10, 'kaartspel', '', 30, 1, 1, 0),
(39, 'Conan', 84.95, 'Conan is een op een miniatuur gebaseerd bordspel dat een speler plaatst, de opperheer, die hordes wilde stamleden, niet-goede slapers en ondode minions bestuurt tegen 1 tot 4 spelers die de legendarische Conan en zijn mede-avonturiers incarneren. De gameplay is asymetrisch, omdat de opperheer over een grote selectie modellen en doelstellingen beschikt die van hemzelf zijn, terwijl de dappere helden vanuit het perspectief van een eerste persoon worden gespeeld, net als in een rollenspel. Een avontuur kan in 1 uur worden gespeeld op een van de prachtige spelborden terwijl je je verstand, durf en tactisch inzicht ten opzichte van je tegenstander gebruikt.', 'conan.jpg', 14, 2, 5, 'overige', '', 90, 0, 0, 1),
(40, 'Set', 12.95, 'Er liggen 12 kaarten met gekleurde symbolen op tafel. De symbolen hebben vier eigenschappen in drie variaties: een kleur, een hoeveelheid, een vulling en een vorm. Alle spelers zoeken nu tegelijkertijd naar een set. Een set bestaat uit drie kaarten, waarvan de variatie van de eigenschappen volledig gelijk is of helemaal verschillend. Als je een set ziet, roep je \"SET!\". Het spel stopt even en je laat zien welke drie kaarten volgens jou een set vormen. Heb je gelijk, dan mag je de kaarten houden. Zo niet, dan leg je ze weer terug en mag je pas weer meedoen nadat een andere speler een correcte set heeft gevonden. Na het pakken van een set worden de kaarten op tafel weer aangevuld. Wie heeft aan het einde van het spel de meeste kaarten?', 'set.jpg', 6, 2, 8, 'kaartspel', '', 20, 0, 1, 0),
(41, 'Regenwormen', 12.95, 'Dit snelle compacte dobbelspelletje kun je op elk moment en overal spelen. Het duurt niet langer dan een half uurtje en het formaat zorgt ervoor dat je het thuis, in de trein of op de campingtafel kunt neerleggen. Iedereen die tot 36 kan tellen, kan meedoen! Als je aan de beurt bent, gooi je met 8 dobbelstenen. Je legt nu alle dobbelstenen met hetzelfde getal of met een worm opzij. Daarna gooi je met de resterende dobbelstenen en legt nu alle dobbelstenen met een ander getal opzij. Als je totaal hoger is dan 20 en je hebt ten minste één worm gegooid, mag je de steen met het betreffende getal van tafel of zelfs van een andere speler pakken! Maar neem je teveel risico en gooi je alleen maar getallen die je al eens hebt gepakt, dan ben je af en moet je juist een steen inleveren. Op elke steen staan een aantal regenwormen. Wie aan het einde van het spel de meeste regenwormen heeft, is de winnaar. Probeer Regenwormen nu zelf uit met onze online probeervariant.', 'regenwormen.jpg', 8, 2, 7, 'dobbelspel', '', 30, 0, 0, 0),
(42, 'Dokter Bibber', 39.95, 'Je patiënt Sam voelt zich helemaal niet lekker. Ben jij een goede dokter en kun je hem zonder te bibberen weer beter maken, of raak je de zijkanten? Pak het pincet en probeer al zijn gekke kwalen eruit te halen. Kun jij die nare kikker uit Sam z’n keel halen en die verrekte spier repareren? Als je de zijkanten raakt gaat de neus branden en ben je af. De dokter die de meeste kwalen verwijdert wint het spel en maakt Sam beter.', 'dokter_bibber.jpg', 6, 2, 4, 'overige', '', 15, 1, 0, 0),
(43, 'Jenga', 26, 'Test hoe vast jouw hand is met Jenga Classic. Spanning, strategie en inzicht zijn nodig om de toren niet in jouw beurt te laten vallen! \r\n\r\nBouw de toren. Leg drie blokken per laag, elke volgende laag haaks op de vorige. Gebruik zo nodig de stapelhoes. Haal met één hand een blok uit de toren, op een willekeurig plek onder de bovenste complete laag. Je mag de blokken aanraken om een losse te vinden. Leg het blok bovenop de toren. Wacht ongeveer 10 seconden. Als de toren instort, ben je af. Als de toren blijft staan, is de volgende speler aan de beurt. Als je in je eentje speelt, probeer je je eigen hoogste toren te verslaan. Zorg dat jij de laatste speler bent die een blok stapelt zonder dat de toren instort!', 'jenga.jpg', 6, 1, 25, 'denkspel', '', 15, 0, 0, 0),
(44, 'Triominos', 26.95, 'De meest fascinerende variant van Triominos. Nu met een bijzondere dimensie! Een spel van inzicht, tactiek en logica, voor jong en oud.', 'triominos.jpg', 6, 1, 6, 'denkspel', '', 30, 0, 0, 0),
(45, 'Doolhof', 28.95, 'Doolhof - de Ravensburger klassieker met het magische spelbord. Al 30 jaar verschuiven miljoenen mensen de gangen en zoeken ze naar schatten. En nu kan je voor het eerst het doolhof ook in het donker spelen! Nieuwe schatten komen uit het niets tevoorschijn en de gangen lichten op: een fascinerende ervaring die kleine en grote spelers versteld laat staan!\r\n\r\nTelkens veranderen de gangen; het lijkt wel of het spookt. De schat lag net nog daar! Het doolhof lijkt wel betoverd. Wie weet ondanks die betovering toch de geheimzinnige voorwerpen en schatten te vinden? Een geestig spel vol verrassingen.', 'doolhof.jpg', 7, 2, 4, 'bordspel', '', 30, 0, 0, 0),
(46, 'Barricade', 14.95, 'Alle wegen leiden naar hetzelfde doel. Maar je loopt nog niet voorop of medespelers leggen barricades in de weg. Dan komt het aan op zelfbeheersing, tactiek en een beetje geluk! Speelplezier en spanning tot de laatste minuut - hét ideale familiespel van Ravensburger voor oud en jong. Barricade® - een \"evergreen\" onder de spellen. Nu met een extra spelbord op de rugzijde - voor een snel spelletje tussendoor. \r\n', 'barricade.jpg', 8, 2, 4, 'bordspel', '', 60, 0, 0, 0),
(47, 'Gruffalo ', 10.99, 'Help jij Muis door het donkere bos de hongerige vos, uil en slang te ontwijken in Ravensburger The Gruffalo Deep Dark Wood Game? Alles wat je nodig hebt is een beetje geluk, een dobbelsteen en een goed geheugen! \r\n', 'gruffalo.jpg', 3, 2, 4, 'kaartspel', '', 10, 0, 0, 0),
(48, 'Frozen memory', 15.95, 'memory® van Ravensburger is al meer dan 50 jaar het meest geliefde eerste spel dat een kind met andere spelen kan... en hoe! Meestal winnen zij gemakkelijk van volwassenen. Daarnaast oefent het kind spelenderwijs belangrijke vaardigheden zoals concentratie en uithoudingsvermogen. Door de grote kaarten van extra dik karton is deze memory® met afbeeldingen van Disney Frozen al geschikt voor de allerkleinsten.', 'memory_frozen.jpg', 4, 2, 8, 'kaartspel', '', 30, 0, 0, 0),
(49, 'Bob de Bouwer Memory', 16.95, 'Voor het spannende zoeken naar bij elkaar passende kaartjes zijn concentratie en een goed geheugen nodig. Wie weet als eerste waar de 2 bij elkaar horende kaartjes liggen? De kleintjes winnen het vaak gemakkelijk van volwassenen!\r\n', 'memory_bobdebouwer.jpg', 4, 2, 8, 'kaartspel', '', 20, 0, 0, 0),
(50, 'Qwixx', 10.95, 'Bij Qwixx hoef je niet op je beurt wachten - iemand dobbelt en iedereen kan de worp benutten! Hoe meer getallen je op je scoreblad aankruist, des te meer punten je krijgt. Qwixx kan in twee minuten worden uitgelegd en is spannend tot de laatste worp! Dobbel mee en laat je aansteken door de Qwixx-koorts!\r\n', 'qwixx.jpg\r\n', 8, 2, 5, 'dobbelspel', '', 15, 0, 0, 0),
(52, 'Biggen', 13.95, 'Bij het geluksspel Biggen gooi je niet met dobbelstenen, maar met varkentjes. De manier waarop de varkentjes op de tafel landen, bepaalt het aantal punten dat je verdient. \r\n\r\nNaast het gooien met varkentjes, kun je ook punten verdienen door de uitkomst van de worp van je tegenstanders te voorspellen. Raad je het juiste aantal? Dan verdien je natuurlijk punten. Maar, je verliest juist punten als je het verkeerd hebt. Wie als eerste 100 punten bij elkaar gooit, wint. Maar pas op: je hoeft maar een verkeerde worp te gooien en je mag weer van voor af aan beginnen.', 'biggen.jpg', 8, 2, 6, 'dobbelspel', '', 15, 0, 0, 0),
(53, 'Yathzee', 5.95, 'Schud de dobbelstenen in de beker en rol ze op de tafel. Welke combinaties kun je maken met de getallen?', 'yathzee.jpg', 3, 2, 5, 'dobbelspel', '', 20, 0, 0, 0),
(54, 'Catan Dobbelspel', 10.95, 'In dit spannende spel bouwen de spelers Catan worp na worp op. Elke straat en elke nederzetting levert punten op. Een gelukkige hand en tactisch vernuft bepalen wie de beste ontdekker is. Je krijgt een velletje papier waar de uit Catan bekende straten, dorpen en steden op staan. Als je aan de beurt bent, mag je drie keer met de dobbelstenen gooien om een combinatie samen te stellen waar je wat aan hebt. Gooi je geen enkele combinatie, dan krijg je strafpunten. Dat kun je voorkomen door ridders te kopen, die je de mogelijkheid geven om een dobbelsteen naar een bepaalde grondstof te draaien. Dit vlotte dobbelspelletje speel je weg in een klein half uurtje en past prima in je reisbagage. En, zijn je scoreblokken op? Geen nood, je kunt extra scoreblokken bij ons bestellen.', 'catan_snel_kaartspel.jpg', 10, 1, 4, 'dobbelspel', '', 15, 0, 0, 0),
(55, 'Clever', 18.95, 'Tactisch dobbelspel voor het hele gezin. \r\n\r\nDobbel en vul één van je geworpen dobbelstenen in de bijbehorende categorie in. Elke categorie levert op een andere manier punten op. Kies slim en let goed op de overgebleven dobbelstenen. Je moet namelijk elke dobbelsteen met een lager resultaat op het zilveren dienblad aan de andere spelers serveren. Die kunnen daardoor wellicht ook belangrijke punten scoren.\r\n\r\nIn dit dobbelspel zijn alle spelers voortdurend bezig. Daardoor is het tot het einde razend spannend!', 'clever.jpg', 8, 1, 4, 'dobbelspel', '', 30, 0, 0, 0),
(56, 'Verboden slot', 12.95, 'Het uitdagende coöperatieve escape room-spel! Ontsnap zo snel mogelijk uit het geheimzinnige kasteel. Probeer binnen anderhalf uur alle puzzels op te lossen en alle codes te breken. Alleen dan ontsnappen jullie uit de locatie waar jullie opgesloten zitten. Logisch nadenken en doorzettingsvermogen zijn vereist om dit spel tot een goed einde te brengen. En komen jullie er echt niet uit, dan bevat het spel tipkaarten om jullie op het goede spoor te brengen. EXIT: Het Verboden Slot is maar één keer speelbaar omdat het speelmateriaal moet worden beschreven, gevouwen of afgescheurd. Maar net als in een \"echte\" escape room garanderen we een zeer intense puzzel- en speelervaring! De puzzels zijn vrij pittig. Daardoor is het spel vooral geschikt voor fervente puzzelaars en escape room-liefhebbers.', 'verboden-slot.jpg', 12, 1, 4, 'denkspel', '', 45, 0, 0, 0),
(57, 'Rubik\'s Cube', 19.95, 'Dit is de nieuwe Rubik\'s Cube Speed met harde tegels. De traditionele stickers zijn vervangen door kunststof; wat betekent dat er niet meer valsgespeeld kan worden door de stickers te verplaatsen! De Rubik\'s Cube Speed heeft een geheel nieuw mechanisme dat er voor zorgt dat je nog sneller kunt draaien en dat de stenen er tijdens het draaien niet uit springen. \r\nDe Rubik\'s Cube Speed voldoet volledig aan alle WCA regels en voorschriften en is ontworpen met WCA wedstrijden in het achterhoofd. Hij is zorgvuldig getest en verbeterd om de hoogste kwaliteit te waarborgen.\r\n\r\nDeze Rubik’s Cube heeft een speciale veer waardoor de spanning kan worden afgesteld, een nieuwe geavanceerde bolvormige kern en wordt geleverd met prestatie verhogend smeermiddel.', 'rubik.jpg', 8, 1, 1, 'denkspel', '', 30, 1, 1, 0),
(58, 'Squirrels go Nuts', 19.95, 'Verschuif de eekhoorns en verstop de nootjes. De winter komt er aan. Kan jij de eekhoorns helpen om hun wintervoorraad onder de grond te verstoppen? “Squirrels Go Nuts” is een schuifpuzzel met 60 opdrachten van makkelijk tot razend moeilijk\r\nSfeerimpressie', 'squirrels_go.jpg', 8, 1, 1, 'overige', '', 30, 0, 0, 0),
(59, 'Wie is het?', 16.95, 'Dit is het originele Wie is het? raadspel! Dit Wie is het? spel gaat terug naar de staande spelcassettes, in plaats van de cassettes die je vast moet houden. \r\n\r\nElke speler kiest een geheime figuur en probeert dan met behulp van ja- en nee-vragen uit te vinden wie de geheime figuur van de tegenstander is. Als je denkt dat je weet wie de tegenstander heeft gekozen, mag je raden. Maar pas op, want als je fout raadt, verlies je het spel! De spelers kunnen ook een aantal keren tegen elkaar spelen in een toernooi: de eerste speler die 5 keer wint is de Wie is het? kampioen.\r\n', 'wie_is_het.jpg', 6, 2, 2, 'denkspel', '', 15, 1, 0, 0),
(60, 'Trivial Pursuit', 21.95, 'Verzamel je vrienden voor het trivia-spel waarmee het allemaal begon! De klassieke editie van dit Trivial Pursuit spel biedt het bekende en geliefde spel, maar dan met het retro-uiterlijk van de jaren 80! Met de klassieke speelwijze op het bekende speelbord en 2400 vragen in 6 categorieën: Aardrijkskunde, Amusement, Geschiedenis, Kunst & Literatuur, Wetenschap & Natuur, Sport & Ontspanning. Spelers verplaatsen over het bord en beantwoorden vragen. Als een speler op een categorievakje eindigt, kan hij een partje van die kleur verdienen wanneer hij de vraag goed beantwoordt. De eerste speler die 6 verschillend gekleurde partjes verzamelt en de laatste beslissende vraag juist beantwoordt wint! \r\n', 'trivial_pursuit.jpg', 16, 2, 6, 'bordspel', '', 60, 1, 0, 0),
(61, 'Banana Joe', 16.95, 'Banana Joe is een spannend actiespel waar gegarandeerd veel lol mee beleeft wordt.\r\n\r\nDuw de bananen in de gaten van de bananenboom en zet deze in het midden van de tafel. Vervolgens druk je het aapje op de pin in het midde van de bananenboom vast. De speler die het hoogste kan springen, mag beginnen. tijdens de beurt gooit de speler de dobbelsteen en doet wat erop staat: Of 1 banaan pakken en voor je neerleggen, 2 bananen pakken en voor je neerleggen, een banaan aan iemand willekeurig geven of een banaan stelen van iemand anders. Maar pas op, want het aapje kan zomaar opspringen! \r\n\r\nWanneer het aapje in de lucht springt, moeten alle spelers het proberen te vangen voordat het de grond raakt. De speler die het aapje vangt, krijgt een bonus! Als je het aapje hebt gevangen mag je 2 bananen stelen (in totaal) van willekeurige speler(s). Wie de meeste bananen heeft, is de winnaar!', 'banana_joe.jpg', 6, 2, 4, 'overige', '', 20, 0, 0, 0),
(63, 'Twister', 17.95, 'Twister voor uren lachen, gieren, brullen! \r\n\r\nLaat de draaiwijzer draaien en roep de opdrachten. De spelers moeten het genoemde lichaamsdeel zo snel mogelijk naar de genoemde kleur stip verplaatsen. Als je met je knie of elleboog op de mat komt, of als je omvalt, ben je AF! De laatste speler die overblijft, wint Twister.\r\n\r\nDit bekende spel biedt nu 2 extra mogelijkheden om ondersteboven van te raken: steek je hand of voet in de lucht en \"Draaier mag \'t zeggen\", waarbij de draaier een grappige opdracht mag verzinnen. Op de achterkant van de draaiwijzer staan grappige ideeën voor inspiratie. Nog nog meer fun met deze extra moves!\r\n', 'twister.jpg', 6, 1, 24, 'spelkamer', '', 15, 0, 0, 0),
(64, 'Sjoelbak', 79.9, 'Goede kwaliteit sjoelbak voor het hele gezin! Officiele speellengte van 2 meter. Inclusief 30 schijven van gepolijst beukenhout en aflsuitdeksel voor de schijven. Kant en klaar voor gebruik, inclusief handleiding met speelvarianten, stevig verpakt in een kartonnen doos ', 'sjoelbak.jpg', 8, 1, 4, 'spelkamer', '', 15, 1, 0, 0),
(65, 'Automatische kaartenschudmachine', 12, 'De automatische kaartschudder kan 1 of 2 pakjes kaarten tegelijkertijd schudden. Herhaaldelijk handmatig schudden van kaarten zorgt voor beschadiging van je speelkaarten. Nu kunt u de automatische kaartschudder gebruiken, zodat uw kaarten langer als nieuw blijven. De automatische kaartschudder is een eenvoudige, betaalbare, praktische en functionele oplossing.\r\n\r\nHeel makkelijk voor een potje poker, blackjack of elke ander kaartspel, waarbij veelvuldig geschud moeten worden met de kaarten. ', 'kaart_schud_machine.jpg', 8, 1, 30, 'overige', '', 0, 0, 0, 0),
(66, 'Chartered: The Golden Age', 39.99, 'Tijdens het spelen van Chartered: The Golden Age waan je jezelf als koopman in de ontluikende handel van de 17e eeuw. Je bouwt pakhuizen, investeert in diverse producten en je draagt bij aan de groei van Amsterdam. Het doel van het spel is zelf zo veel mogelijk winst te maken, op de juiste plaatsen pakhuizen te bouwen om je tegenstanders te blokkeren en bedrijven nog sneller te laten groeien door overnames. De koopman met het meeste geld, wint het spel. \r\n\r\nZie https://www.kickstarter.com/projects/1564935528/chartered-the-golden-age-0/description voor meer informatie. ', 'chartered_golden_age.png', 10, 2, 6, 'bordspel', '', 60, 0, 0, 1),
(68, 'Damstenen in een Houten Kistje', 7.99, 'Altijd al willen dammen? Houten damstenen gemaakt van Essenhout. De damstenen hebben een diameter van 32 mm. De stenen zitten opgeborgen in een houten kistje met schuifdeksel ', 'damstenen_houten_kistje.jpg', 10, 2, 2, 'overige', '', 0, 0, 0, 0),
(69, 'Secret Hitler', 25, 'Secret Hitler is een dramatisch spel van politieke intriges en verraad in het Duitsland van de jaren 1930. Elke speler wordt willekeurig en in het geheim toegewezen als liberaal of fascist, en één speler is in het geheime Hitler. De fascisten coördineren om wantrouwen te zaaien en hun koelbloedige leider aan de macht te stellen; de liberalen moeten de geheime Hitler vinden en stoppen voordat het te laat is. Het liberale team heeft altijd een meerderheid.', 'secret_hitler.jpg', 17, 5, 10, 'kaartspel', '', 45, 0, 0, 1),
(70, 'Scythe ', 59, 'Het is een tijd van onrust in Europa van de jaren twintig. De nasleep van de eerste wereldoorlog maakt de sneeuw nog donkerder. De kapitalistische stadstaat, die simpelweg bekend staat als ‘De Fabriek’, die de oorlog voedde met zwaar gepantserde mechs, heeft zijn deuren gesloten en trekt de aandacht van verschillende nabijgelegen landen.\r\n\r\nScythe is een game in een alternatieve geschiedenis in de periode van de jaren 1920. Het is een tijd van landbouw en oorlog, gebroken harten en verroeste tandwielen, innovatie en moed. In Scythe vertegenwoordigt elke speler een personage uit een van de vijf facties van Oost-Europa die proberen hun fortuin te verdienen en het aandeel van hun factie in het land rond de mysterieuze fabriek te claimen. Spelers veroveren gebieden, rekruteren nieuwe manschappen, oogsten goederen, verkrijgen nieuwe dorpelingen, bouwen en activeren monsterlijke mechs.', 'scythe.jpg', 16, 1, 5, 'bordspel', '', 60, 0, 0, 1),
(71, 'Massive Darkness', 110, 'Massive Darkness brengt de klassieke fantasy-RPG-ervaring naar het bordspel, met een actievolle campagne boordevol prachtige miniaturen en een gestroomlijnd systeem dat de focus houdt op de acties van de helden, zonder dat je een game-master nodig hebt om de vijanden te besturen.\r\n\r\nKies je held, kies een klas, bepaal welke vaardigheden je je XP aan uitgeeft en krijg buit door de kerkers te doorzoeken of speciale vijanden te doden! Neem het op tegen een groot aantal verschillende vijand typen of omzeil je vijanden door te profiteren van de donkere delen van de kaart.', 'massive_darkness.png', 16, 1, 6, 'bordspel', '', 60, 0, 0, 1),
(72, 'Gloomhaven', 99, 'Gloomhaven is een spel vol tactische gevechten in een aanhoudende wereld van veranderende motieven. Spelers zullen de rol aannemen van een rondtrekkende avonturier met hun eigen speciale vaardigheden en hun eigen redenen om naar deze donkere hoek van de wereld te reizen. Spelers moeten uit noodzaak samenwerken om gevaarlijke kerkers en vergeten ruïnes schoon te ruimen. In dit proces zullen ze hun vaardigheden verbeteren met ervaring en buit, nieuwe locaties ontdekken om te verkennen en plunderen, en een steeds vertakkend verhaal uitbreiden dat wordt aangewakkerd door de beslissingen die ze nemen.', 'gloomhaven.jpg', 16, 1, 4, 'bordspel', '', 30, 0, 0, 1);
INSERT INTO `products` (`product_id`, `product_name`, `product_price`, `product_desc`, `product_img`, `product_age`, `product_min_players`, `product_max_players`, `product_category`, `product_difficulty`, `product_playtime`, `product_classic`, `product_travelversion`, `product_kickstarter`) VALUES
(73, 'Zombicide Black Plague', 100, 'Zombicide: Black Plague neemt de zombie-apocalyps mee naar een fantastische middeleeuwse setting! De geheimzinnige krachten van de Necromancers hebben een zombie-invasie in het tijdperk van zwaarden en tovenarij ontketend, en het is aan je groep overlevenden om niet alleen in leven te blijven tijdens deze donkere tijden, maar om het rijk terug te nemen en degenen te straffen die verantwoordelijk zijn voor de Apocalypse!', 'zombicide_black_plague.png', 18, 1, 6, 'bordspel', '', 60, 0, 0, 1),
(75, 'Dark Souls: The Board Game', 100, 'Darks Souls: The Board Game is een bruut en moeilijk ontdekkingsspel voor 1-4 spelers. Bereid je voor om te sterven!\r\n\r\nDe game beschikt over een mechanisme voor “snel opzetten, lang spelen” dat je snel in het spel brengt en de locatie tijdens je verkenning vergroot en aanpast. Het gevoel van gevaar is voelbaar terwijl je nieuwe locaties en de monsters ontdekt die op deze donkere plaatsen wonen. Het gevecht mechanisme en het vijandige gedragssysteem dwingen je tot diepgaand strategisch keuzes en slim beheer van je uithoudingsvermogen om te overleven.', 'dark_souls.png', 16, 1, 4, 'bordspel', '', 45, 0, 0, 1),
(76, 'Ganzenbord', 14.95, 'Deze klassieker en bestseller is geliefd bij kinderen en volwassenen in de hele wereld. e spelers moeten proberen met hun gans als eerste het doelveld te bereiken.\r\n\r\nInhoud:\r\n1 spelbord\r\n6 houten ganzen in verschillende kleuren\r\n2 dobbelstenen\r\nspelregels', 'ganzenbord.jpg', 6, 2, 4, 'bordspel', '', 30, 1, 0, 0),
(77, 'Roulette bak', 99.99, 'Deze roulettebak is zwart, gemaakt van MDF en inclusief 2 kogeltjes. Diameter 36cm.\r\n\r\nDe roulettebak is gemaakt van mooi gelakt mdf. De onderkant is voorzien van vilt, zodat de bak niet zal krassen. In de bak zit een metalen houder voor het wiel. Ook het wiel is gemaakt van metaal. Dit metaal is voorzien van een (koperen?) coating wat het geheel een luxe uitstraling geeft. Door de zware uitvoering draait het wiel lang door.', 'roulette.jpg', 12, 1, 0, 'overige', '', 15, 0, 0, 0),
(78, 'Ultimate Guard Play-Mat', 22.99, 'Ultimate Guard Play-Mat 60 Mystic Space 61 x 61 cm\r\n\r\n- Protects gaming cards and accessories during gameplay!\r\n- Extra thick! 2 mm Mat\r\n- Soft cushioned Play-Mat\r\n- Anti-slip backside for maximum gaming grip\r\n- High quality fabric for perfect dice rolling effect\r\n- Size: approx. 61 x 61 cm', 'playmat.jpg', 12, 1, 0, 'overige', '', 15, 0, 0, 0),
(79, 'Smart Games IQ-Fit', 11.49, 'Hou je hersens fit met de fantastische IQ-Fit - Reiseditie.\r\n\r\nLeg de 3D-puzzelstukken op het spelbord zodat een 2D-afbeelding ontstaat zonder gaten.\r\n\r\nEen super-leuk denkspel met 120 opdrachten waarbij je \"diep\" moet nadenken om de oplossing te vinden.', 'iq_fit.jpg', 6, 1, 1, 'denkspel', '', 15, 0, 1, 0),
(80, 'Rummikub - Tin - Reiseditie', 15.99, 'Het overbekende familiespel Rummikub in een handige, stevig opbergblik. Ideaal voor op reis! Maak mooie cijferreeksen met de gekleurde cijfers op je plankje. Wie legt de slimste combinaties? Een spel dat inzicht, durf en tactiek combineert.\r\n\r\nSpelers moeten zo snel mogelijk de tegels op hun bordje kwijt zien te raken door de juiste combinaties te leggen. Dat kan met de tegels van je bordje of met de tegels die al op tafel liggen.\r\n\r\nIn Rummikub zijn de populairste elementen van een aantal bekende spelen, zoals Mah-Jongg, domino, jokeren en aspecten van het schaakspel verwerkt.\r\n\r\nVoor 2 tot 4 spelers vanaf 6 jaar.', 'rummikub_travel.jpg', 6, 2, 4, 'denkspel', '', 60, 0, 1, 0),
(81, 'Jump in', 14.95, 'Help de konijntjes zich al springend te verstoppen!\r\nSpring over andere konijnen, paddestoelen en vossen, totdat alle konijnen veilig in een hol zitten. Een origineel puzzelspel met 60 opdrachten in een handig formaat met deksel, ideaal voor onderweg.\r\n\r\nSpeelplezier voor jong én oud\r\n60 opdrachten, van gemakkelijk tot moeilijk\r\nPlanning, logisch & probleemoplossend denken\r\nLeeftijd vanaf 7 jaar\r\nReisspel in handige opbergdoos\r\n', 'Jump-in.jpg', 7, 1, 1, 'denkspel', '', 15, 0, 1, 0),
(82, 'Tafelvoetbal', 89.95, 'De Buffalo Voetbaltafel Winner is ideaal voor jongeren tot 12 jaar. \r\n', 'tafelvoetbal.jpg', 4, 2, 4, 'spelkamer', '', 15, 0, 0, 0),
(83, 'Professioneel tafelvoetbal', 445, 'De populaire Big Brother van Buffalo is een uiterst robuuste tafel met een mooi en solide speelveld. Het spelen op deze voetbaltafel is niet alleen vermakelijk, maar ook goed voor de oog-handcoördinatie en het reactievermogen! \r\nNodig familie en vrienden uit en beleef samen uren speelplezier met deze Big Brother. \r\nInclusief 4 luxe witte balletjes en handmatige scoreteller.\r\nZeer solide voetbaltafel\r\nAfm. 140 x 76 x 86 cm (lbh)\r\nSpeelveld: 119 x 68 cm (lb)\r\nIngefreesde handmatige scoretellers\r\nBalinwerpsleuf\r\nSchuine hoeken: Momentum Control\r\nGewicht 73kg\r\nNiet geschikt voor commercieel gebruik', 'tafelvoetbal_groot.jpg', 4, 2, 4, 'spelkamer', '', 15, 0, 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `user_id` int(10) UNSIGNED NOT NULL,
  `user_email` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `user_password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `role` enum('user','admin') COLLATE utf8_unicode_ci NOT NULL,
  `user_first_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `user_middle_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `user_last_name` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `user_place` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `user_streetname` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `user_housenumber` int(10) NOT NULL,
  `user_number_suffix` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `user_zipcode` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `user_phone` varchar(15) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `user_email`, `user_password`, `role`, `user_first_name`, `user_middle_name`, `user_last_name`, `user_place`, `user_streetname`, `user_housenumber`, `user_number_suffix`, `user_zipcode`, `user_phone`) VALUES
(1, 'henk@henk.nl', '$2y$12$ZNTMUA6TYk47jZ4ihWRmfOfLUvztzpgr5f8oQjgiktPEp4Z2lNPNi', 'user', '', '', '', '', '', 0, '', '', ''),
(2, 'aa@aa.com', '$2y$12$9.kCQPmZST.w8KrOdJZAM.rKXUDymLGCHhIARn9PBPNknmLZ/Xru6', 'user', '', '', '', '', '', 0, '', '', ''),
(3, 'ka@ka.nl', '$2y$12$18wAT.pQgSHef3OZDe.mjOm5h.6c5aX9mF7M1/NYSsJ/CGAzvj/MS', 'user', '', '', '', '', '', 0, '', '', ''),
(4, 'jira@verk.nl', '$2y$12$BiYBKv4dEA7yUJLpFlnYTehmv0r1AK8hmdoEe3wLJiK1nis2d4q/e', 'user', '', '', '', '', '', 0, '', '', ''),
(5, 'henk@code.nl', '$2y$12$..1c/VvTPicXd/lA2jQfv.4eBXe6RcYbHSkWGkvweeH/d4cB17AW.', 'user', '', '', '', '', '', 0, '', '', ''),
(6, 'piet@piet.com', '$2y$12$8sE5an.ssRm0/Gz5sbinjuNXj.VbWCCigm8s9xtMXZv4RfqiLGO/e', 'user', '', '', '', '', '', 0, '', '', ''),
(7, 'piet@piet.es', '$2y$12$fTIfMNPKxO.mpI8P0K9jTul70Fx2hnE3fuQ6STMoVuNRfjbe44faa', 'user', '', '', '', '', '', 0, '', '', ''),
(8, 'test@test.nl', '$2y$12$fEcKR55m4LCzv5iA5lgRM.QTc73NPB4DJv7TTz2lg1ZoBrXnbI7nq', 'user', '', '', '', '', '', 0, '', '', ''),
(9, 'aap@aap.nl', '$2y$12$7EmfhbcdSdMt3rKuVpTCmuctWXQSRoliOxjF35oPvru/kUvHxukPO', 'user', '', '', '', '', '', 0, '', '', ''),
(10, 'wilbert@wilbert.nl', '$2y$12$bxI5eA/F2Nj3DG6eKcJozuK8qHS7NPKqthdbJamy7WNJ8ZI4VDVm6', 'user', '', '', '', '', '', 0, '', '', ''),
(11, 'noob@noob.nl', '$2y$12$oKIsutTMRQ85jjTGa1bD/u8//aKZ7hHLMhPerZzFTvx7Ipo39Zse.', 'user', '', '', '', '', '', 0, '', '', ''),
(12, 'chinagarden@chinagarden.nl', '$2y$12$YGsX2H0qO/nU6TdoLLhi9us06nOUdfy7l9tcCc/RY3ub/DHglFoxC', 'user', '', '', '', '', '', 0, '', '', ''),
(19, 'noobie@noobie.nl', '$2y$12$3VAXiJrf4YWIrwic63r5A.mrWqp0dowbjZ7UBRrnOGXOsuJrZTygu', 'user', '', '', '', '', '', 0, '', '', ''),
(35, 'thomas@techsnorremans.nl', '$2y$12$melDCn/rpKFyE3YCzmsG8O9UyGxgRbpGdy9DrbJIyRPH/uaIwpBLm', 'user', '', '', '', '', '', 0, '', '', ''),
(39, 'testreg@test.reg.nl', '$2y$12$rAYQvqlSQhj/f1j8v2Q9jOuAbHGh.hmCnTv5ifGaopxCK2KuHYwoW', 'user', '', '', '', '', '', 0, '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`product_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `user_email` (`user_email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=84;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
